bplaetevoet_home_index:
    pattern:  /
    defaults: { _controller: BplaetevoetHomeBundle:Home:index }

bplaetevoet_home_homepage:
    pattern:  /home
    defaults: { _controller: BplaetevoetHomeBundle:Home:index }
    
bplaetevoet_home_projectlist:
    pattern: /projects
    defaults: { _controller: BplaetevoetHomeBundle:Home:projectlist }
    
bplaetevoet_home_over:
    pattern: /over
    defaults: { _controller: BplaetevoetHomeBundle:Home:over }
    
bplaetevoet_home_contact:
    pattern: /contact
    defaults: { _controller: BplaetevoetHomeBundle:Home:contact }

admin_login:
    pattern: /login
    defaults: { _controller: BplaetevoetHomeBundle:Admin:login }

/login_check:
    pattern: /admin/login_check
     
/logout:
    pattern: /admin/logout
   
    
bplaetevoet_admin_adminmenu:
    pattern: /admin
    defaults: { _controller: BplaetevoetHomeBundle:Admin:index }
    
bplaetevoet_admin_addskill:
    pattern: /admin/addskill
    defaults: { _controller: BplaetevoetHomeBundle:Admin:addskill }
    
bplaetevoet_admin_editskill:
    pattern: /admin/editskill/{skillnaam}
    defaults: { _controller: BplaetevoetHomeBundle:Admin:editskill }
    
bplaetevoet_admin_addproject:
    pattern: /admin/addproject
    defaults: { _controller: BplaetevoetHomeBundle:Admin:addproject }
    
bplaetevoet_admin_editproject:
    pattern: /admin/editproject/{projectnaam}
    defaults: { _controller: BplaetevoetHomeBundle:Admin:editproject }
    
bplaetevoet_admin_addimage:
    pattern: /admin/addimage
    defaults: { _controller: BplaetevoetHomeBundle:Admin:addafbeelding }
    
bplaetevoet_admin_addfullproject:
    pattern: /admin/test
    defaults: { _controller: BplaetevoetHomeBundle:Admin:test }
